//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aankoopgeschiedenis.
        /// </summary>
        public static string Aankoopgeschiedenis {
            get {
                return ResourceManager.GetString("Aankoopgeschiedenis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezoekers.
        /// </summary>
        public static string Bezoekers {
            get {
                return ResourceManager.GetString("Bezoekers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        public static string Clubs {
            get {
                return ResourceManager.GetString("Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitie.
        /// </summary>
        public static string Competitie {
            get {
                return ResourceManager.GetString("Competitie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo.
        /// </summary>
        public static string Hallo {
            get {
                return ResourceManager.GetString("Hallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggen.
        /// </summary>
        public static string Inloggen {
            get {
                return ResourceManager.GetString("Inloggen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreren.
        /// </summary>
        public static string Registreren {
            get {
                return ResourceManager.GetString("Registreren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadions.
        /// </summary>
        public static string Stadions {
            get {
                return ResourceManager.GetString("Stadions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal.
        /// </summary>
        public static string Taal {
            get {
                return ResourceManager.GetString("Taal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitloggen.
        /// </summary>
        public static string Uitloggen {
            get {
                return ResourceManager.GetString("Uitloggen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw aankopen.
        /// </summary>
        public static string Uw_aankopen {
            get {
                return ResourceManager.GetString("Uw aankopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedstrijden.
        /// </summary>
        public static string Wedstrijden {
            get {
                return ResourceManager.GetString("Wedstrijden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winkelwagentje.
        /// </summary>
        public static string Winkelwagentje {
            get {
                return ResourceManager.GetString("Winkelwagentje", resourceCulture);
            }
        }
    }
}
