//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoetbalTicketStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonnement
    {
        public int Id { get; set; }
        public int Clubid { get; set; }
        public decimal Prijs { get; set; }
        public string Bezoekerrijksregisternummer { get; set; }
        public int VakTypeId { get; set; }
        public string AspNetUsersId { get; set; }
        public int BestellingId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Bezoeker Bezoeker { get; set; }
        public virtual Club Club { get; set; }
        public virtual VakType VakType { get; set; }
        public virtual Bestelling Bestelling { get; set; }
    }
}
