//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoetbalTicketStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_ShoppingCartData
    {
        public int Id { get; set; }
        public int BestellingId { get; set; }
        public int Ticketid { get; set; }
        public decimal Prijs { get; set; }
        public int WedstrijdId { get; set; }
        public int Hoeveelheid { get; set; }
    
        public virtual dbo_Bestelling dbo_Bestelling { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual Wedstrijd Wedstrijd { get; set; }
    }
}
