//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoetbalTicketStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.dbo_ShoppingCartData = new HashSet<dbo_ShoppingCartData>();
        }
    
        public int Id { get; set; }
        public string Gebruikerid { get; set; }
        public decimal Prijs { get; set; }
        public string Bezoekerrijksregisternummer { get; set; }
        public int Vakid { get; set; }
        public bool Bevestigd { get; set; }
        public int BestellingId { get; set; }
        public int Wedstrijdid { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Bezoeker Bezoeker { get; set; }
        public virtual dbo_Bestelling dbo_Bestelling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbo_ShoppingCartData> dbo_ShoppingCartData { get; set; }
        public virtual Vak Vak { get; set; }
        public virtual Wedstrijd Wedstrijd { get; set; }
    }
}
