//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoetbalTicketStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VoetbalstoreEntities : DbContext
    {
        public VoetbalstoreEntities()
            : base("name=VoetbalstoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Abonnement> Abonnements { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Bestelling> Bestellings { get; set; }
        public virtual DbSet<Bezoeker> Bezoekers { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<ShoppingCartData> ShoppingCartDatas { get; set; }
        public virtual DbSet<Stadion> Stadions { get; set; }
        public virtual DbSet<Taal> Taals { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Vak> Vaks { get; set; }
        public virtual DbSet<VakType> VakTypes { get; set; }
        public virtual DbSet<Wedstrijd> Wedstrijds { get; set; }
    }
}
